name: Sync To Gitee

on:
  workflow_dispatch:  # 修改点：改为手动触发
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Sync to Gitee
        uses: wearerequired/git-mirror-action@master
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_PRIVATE_KEY }}
        with:
          source-repo: "git@github.com:tlju/niuma_gui.git"
          destination-repo: "git@gitee.com:tlju/niuma_gui.git"
